module main;

class Exception {
    lib.String message;

    fn void constructor(lib.String message) {
        self.message = message;
    }
}

class TestException extends Exception {
    fn void constructor() {
        self.message = "TestException static message";
    }
}

class Test {
    fn void foo() throws Exception {
        throw new Exception("normal exception message");
    }

    fn void bar() throws TestException {
        throw new TestException();
    }
}

static fn i32 Main() {
    let Test obj = new Test();
    try {
        obj.foo();
    } catch Exception e {
        lib.IO.println(e.message);
    }

    try {
        obj.bar();
    } catch Exception e {
        lib.IO.println(e.message);
    }

    return 0;
}
